In [2]:
import pandas as pd
df = pd.read_csv('final_results_long_format.csv')

In [3]:
df['answer_length'] = df['answer'].apply(lambda x: len(x.split()))
df['question_length'] = df['question'].apply(lambda x: len(x.split()))

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

#allah akbar
vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(df['answer'])

tfidf_scores = tfidf_matrix.mean(axis=1)

df['tfidf_score'] = np.array(tfidf_scores).flatten()

df.head()

,source,question,answer,writer,answer_length,question_length,tfidf_score
0,reddit_eli5,Why do some animals become trained more easily...,Imagine you have a toy train. Some toy trains...,answer_gemini,150,23,0.000091
1,reddit_eli5,How does Nintendo 's labo work ? I just do n't...,"['In conjunction with the software , the IR se...",human_answers,498,38,0.000129
2,reddit_eli5,How do they know the Chechens being hunted dow...,['The authorities in the case would have gathe...,chatgpt_answers,129,44,0.000081
3,reddit_eli5,How are emulators written ? I only have very b...,['Emulators are programs that allow a computer...,chatgpt_answers,160,53,0.000079
4,reddit_eli5,"Affirmative action . Thanks , I 'm not america...","['In the US , pretty much all blacks originall...",human_answers,650,24,0.000133

In [6]:
df.groupby('writer')['answer_length'].mean().reset_index()

            writer  answer_length
0    answer_gemini     203.964260
1  chatgpt_answers     186.048476
2    human_answers     350.887667